/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2cUBiTLHqVQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"

import React, { useState, useEffect } from 'react';

export function ProgressLoader() {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const duration = 1500; // 2.5 seconds
    const startTime = Date.now();
    
    const updateProgress = () => {
      const elapsed = Date.now() - startTime;
      const newProgress = Math.min((elapsed / duration) * 100, 100);
      setProgress(newProgress);

      if (newProgress < 100) {
        requestAnimationFrame(updateProgress);
      }
    };

    updateProgress();
  }, []);

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="space-y-4 text-center">
        <p className="text-lg font-medium text-foreground">
          Please wait while we fetch the endpoints from your Github
        </p>
        <div className="w-full max-w-md">
          <Progress value={progress} className="h-3 rounded-full bg-muted" />
        </div>
      </div>
    </div>
  );
}

// // Assuming Progress is a component that takes `value` as a prop
// const Progress = ({ value, className }) => (
//   <div className={`relative ${className}`}>
//     <div className="absolute inset-0 bg-primary" style={{ width: `${value}%` }}></div>
//   </div>
// );