/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mHa1YxVojTn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"

export function TabSwitch() {
  const [activeTab, setActiveTab] = useState("static")
  return (
    (<div className="w-full max-w-md mx-auto">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="border-b">
        <TabsList className="flex">
          <TabsTrigger
            value="static"
            className="flex-1 py-2 text-center font-medium transition-colors hover:bg-muted/50 data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-primary">
            Static
          </TabsTrigger>
          <TabsTrigger
            value="dynamic"
            className="flex-1 py-2 text-center font-medium transition-colors hover:bg-muted/50 data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-primary">
            Dynamic
          </TabsTrigger>
        </TabsList>
        <TabsContent value="static" className="py-6">
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Static Content</h2>
            <p>This is some static content that doesn't change.</p>
            <p>
              It could be information about the product, a list of features, or anything else that doesn\'t need to be
              fetched from an API.
            </p>
          </div>
        </TabsContent>
        <TabsContent value="dynamic" className="py-6">
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Dynamic Content</h2>
            <div />
          </div>
        </TabsContent>
      </Tabs>
    </div>)
  );
}
