/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Sqp40GVbUsc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Archivo } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Vulnerabilities() {
  return (
    (<div className="container mx-auto py-8 px-4 md:px-6">
      <h1 className="text-3xl font-bold mb-6">Vulnerable API Attacks</h1>
      <div className="grid gap-6">
        <div className="bg-background rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-4">SQL Injection</h2>
          <div className="grid grid-cols-1 gap-4">
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Endpoint</h3>
              <p className="text-base font-medium">/api/users/id</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Status Code</h3>
              <p className="text-base font-medium">500</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Headers</h3>
              <ul className="text-base font-medium space-y-2">
                <li>Content-Type: application/json</li>
                <li>Authorization: Bearer token</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Message</h3>
              <p className="text-base font-medium">
                The API is vulnerable to SQL injection, allowing attackers to execute arbitrary SQL queries and
                potentially gain unauthorized access to sensitive data.
              </p>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-4">Cross-Site Scripting (XSS)</h2>
          <div className="grid grid-cols-1 gap-4">
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Endpoint</h3>
              <p className="text-base font-medium">/api/comments</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Status Code</h3>
              <p className="text-base font-medium">200</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Headers</h3>
              <ul className="text-base font-medium space-y-2">
                <li>Content-Type: application/json</li>
                <li>X-CSRF-Token: token</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Message</h3>
              <p className="text-base font-medium">
                The API is vulnerable to Cross-Site Scripting (XSS) attacks, allowing attackers to inject malicious
                scripts into the application and potentially steal user data or perform unauthorized actions.
              </p>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-4">Broken Authentication</h2>
          <div className="grid grid-cols-1 gap-4">
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Endpoint</h3>
              <p className="text-base font-medium">/api/login</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Status Code</h3>
              <p className="text-base font-medium">200</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Headers</h3>
              <ul className="text-base font-medium space-y-2">
                <li>Content-Type: application/json</li>
                <li>User-Agent: user-agent</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Message</h3>
              <p className="text-base font-medium">
                The API is vulnerable to Broken Authentication, allowing attackers to gain unauthorized access to user
                accounts by exploiting weaknesses in the authentication and session management mechanisms.
              </p>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-4">Sensitive Data Exposure</h2>
          <div className="grid grid-cols-1 gap-4">
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Endpoint</h3>
              <p className="text-base font-medium">/api/users/id/profile</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Status Code</h3>
              <p className="text-base font-medium">200</p>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Headers</h3>
              <ul className="text-base font-medium space-y-2">
                <li>Content-Type: application/json</li>
                <li>Authorization: Bearer token</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-medium text-muted-foreground">Message</h3>
              <p className="text-base font-medium">
                The API is vulnerable to Sensitive Data Exposure, allowing attackers to access sensitive user
                information, such as passwords, credit card numbers, or other personal data, which could lead to
                identity theft or financial fraud.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}
